spring.application.name=vacunacion-spring

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/spring_vacunacion?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=SpringEduar123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.messages.basename=messages
spring.messages.encoding=UTF-8

logging.level.co.sena.cimm.adso=DEBUG
logging.level.org.hibernate.SQL=DEBUG