spring.application.name=AppDonacion

server.port=8080

spring.datasource.url=jdbc:mysql://kodama.proxy.rlwy.net:19086/railway
spring.datasource.username=root
spring.datasource.password=zjMLtMVwXOPxKDpeFixrYySfvvpbzwNJ

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.messages.basename=messages
spring.messages.encoding=UTF-8

logging.level.sena.adso=DEBUG
logging.level.org.hibernate.SQL=DEBUG

jwt.secret=3b7b7f6aff4f8bd5572e5fe1aed7cb7b1e00405bced754ff54eb4dcaa4eba79a7332c2b2677ee7c13c3faa5201795f1c566fbd033430ff998edbb275a396ee3a
jwt.expiration=86400000